### ISSUE TITLE
Can't Add Enchantments to Weapons or Armor

### ISSUE THREAD

**Issue by DumbXBoxAcct** [cleannrooster/arch_rpgmana#1]
Loving the mod, especially the Archon integration!  The only thing that isn't working for me is applying the enchantments provided (Lucidity, Manafused, Inspired, etc.) to weapons and armor.  

I realize that certain enchantments are specific to either weapons or armor, but when I attempt to use an anvil with the enchanted book and the appropriate type of item to apply the enchantment, there's an "X" on the arrow between them.  Likewise, when I attempt to use the "/enchant" command to apply the enchantment while holding the appropriate item, I get a message saying "Netherite Chestplate (or whatever the item is) cannot support this enchantment."

Oddly, if I use the "Mind-Over-Matter" enchantment, which doesn't have a corresponding Enchanted Book, to enchant a helmet using the "/enchant" command, it works!  Wondering if this is because "Mind-Over-Matter's" Public declaration in the "MindOverMatter.java" file has a different "super" section from the other spells "super(weight, EnchantmentTarget.ARMOR_HEAD, slotTypes)"  The others just have "super(weight, type, slotTypes)"  

I downloaded your source and tried changing the "super" sections for a couple of spells, but when I ran "gradlew build" it errored out because it couldn't resolve the location of "TinyConfig 2.3.2" from the path in "build.gradle."

I'm running MC 1.20.1 with Fabric Loader 0.15.11 and the latest version of "arch-rpgmana" (v. 1.0.8.4), along with the latest version of Archon (0.7.0) and have tried it with nothing but the necessary mods themselves and their dependencies loaded (Spell Engine 0.15.7 and Spell Power Attribute 0.11.0, et al) and I still can't apply the enchantments provided in the mod, so I'm hoping that you can help.

**Comment by cleannrooster** [comment]
Hi, I'll look into it

**Comment by cleannrooster** [comment]
I looked into it, and this is actually a result of a change on Spell Power's end to make spell related enchantments only show up on spell related armors. Considering that this is a change that Daedelus thought would be good and because I agree with mana only showing up on spell gear, I will keep it the way it is.
